table MeasuresTable
	lineageTag: d25df006-fd9b-4578-9a32-e01661636958

	measure M_LastRefresh = MAXX(DataRefresh, DataRefresh[RefreshTimestamp])
		formatString: General Date
		lineageTag: 072c2e67-226b-47c7-b293-2235cda9b7c2

	measure M_RefreshStatus = "Data last refreshed on: " & FORMAT([M_LastRefresh], "DD/mm/yyyy hh:mm AM/PM")
		lineageTag: 9a04dc1c-fd87-4308-9ed3-29adee75dc19

	measure TotalChangeRequests = COUNTROWS(fact_change_request)
		formatString: 0
		lineageTag: bbd23e04-8a3b-4f9a-9920-296f6204e5bc

	measure ChangeRequestsExcludingInfoNormalOT =
			CALCULATE(
			    COUNTROWS(fact_change_request),
			    dim_change_type[is_excluded_from_standard_count] = 0
			)
		formatString: 0
		lineageTag: f52248b4-7d9d-47ba-87c7-2e3cc45617a9

	measure TotalP1P2Incidents =
			CALCULATE(
			    COUNTROWS(fact_tech_incident),
			    dim_incident_priority[is_high_priority] = 1
			)
		formatString: 0
		lineageTag: f2635d1b-3ae5-4ad1-96a6-f0d4b40b27a9

	measure TotalP1P2Incidents_NotInformationNormalOT =
			CALCULATE(
			    COUNTROWS(fact_tech_incident),
			    dim_incident_priority[is_high_priority] = 1,
			    NOT ISBLANK(fact_tech_incident[change_request_code]),
			    CALCULATETABLE(
			        VALUES(fact_change_request[change_request_code]),
			        dim_change_type[is_excluded_from_standard_count] = 0
			    )
			)
		formatString: 0
		lineageTag: 75dc1e20-0951-421b-9cff-40f56d7b0fca

	measure '%ChangesCausedP1P2' =
			FORMAT(
			    DIVIDE(
			        [TotalP1P2Incidents_NotInformationNormalOT],
			        [ChangeRequestsExcludingInfoNormalOT]
			    ),
			    "0.00%"
			)
		lineageTag: c67120b4-b639-4a3c-852e-78d413c9f27e

	column Column
		isHidden
		formatString: 0
		lineageTag: 62f4b31b-ce83-4d95-8bbf-92388e231f55
		summarizeBy: sum
		isNameInferred
		sourceColumn: [Column]

		annotation SummarizationSetBy = Automatic

	partition MeasuresTable = calculated
		mode: import
		source = Row("Column", BLANK())

	annotation PBI_Id = d6e86b2c08594fdd98c3d32d029bef2a

