table Date
	lineageTag: 05476528-1fe8-48a2-910c-afb7b54a762f
	dataCategory: Time

	column YearPeriod
		dataType: string
		lineageTag: 25bddfdd-0a39-49f6-829d-7243a5462d30
		summarizeBy: none
		sourceColumn: YearPeriod

		annotation DataTypeAtRefresh = String#####not a type

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column Year
		dataType: int64
		lineageTag: 48fb36f2-e5cb-4814-8cfa-1291dd181dca
		summarizeBy: sum
		sourceColumn: Year

		annotation DataTypeAtRefresh = Int64#####not a type

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Period
		dataType: string
		lineageTag: 047dd02c-f972-4393-b981-937a967a15e5
		summarizeBy: none
		sourceColumn: Period

		annotation DataTypeAtRefresh = String#####not a type

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column Date
		dataType: dateTime
		isKey
		formatString: General Date
		lineageTag: 0cff79f6-387a-42ca-a7af-3fc5087594f1
		summarizeBy: none
		sourceColumn: Date

		variation Variation
			isDefault
			relationship: db9c55a6-9978-4ac0-88b4-4f07ed8945a3
			defaultHierarchy: LocalDateTable_39c22ddb-27f3-4e6c-8a44-a3380850fcb4.'Date Hierarchy'

		annotation DataTypeAtRefresh = DateTime#####not a type

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: string
		lineageTag: ae2ece85-a7ac-4e1d-bcbc-ea360c09fe3b
		summarizeBy: none
		sourceColumn: Month
		sortByColumn: Period

		annotation DataTypeAtRefresh = String#####not a type

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column QtrID
		dataType: string
		lineageTag: 28a1ea7d-3a63-4d0c-af11-7fc0b1b6fe0f
		summarizeBy: none
		sourceColumn: QtrID

		annotation DataTypeAtRefresh = String#####not a type

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column Qtr
		dataType: string
		lineageTag: a07e748f-5f45-44a6-949a-ea5efc501bf8
		summarizeBy: none
		sourceColumn: Qtr

		annotation DataTypeAtRefresh = String#####not a type

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	hierarchy YQM
		lineageTag: 03442dee-9881-4a53-8a72-94991d2daf82

		level Year
			lineageTag: c88e9981-2578-4d64-a40e-177159720d8e
			column: Year

		level Qtr
			lineageTag: f31b3ccb-d76a-4940-a2e1-445ce7042c2a
			column: Qtr

		level Month
			lineageTag: 604d6bec-6de2-4c93-b2be-44f1accd92b4
			column: Month

	partition Date = m
		source =
				let
				    Source = Sql.Database(".", "IP", [Query="SELECT#(lf)       concat([Year], [period]) YearPeriod#(lf)#(tab)  ,[Year]#(lf)      ,[Period]#(lf)      ,[Date]#(lf)      ,[Month]#(lf)      ,[QtrID]#(lf)      ,[Qtr]#(lf)  FROM [MDS].[mdm].[fiscalperiod]"]),
				    #"Renamed Columns" = Table.RenameColumns(Source, {{"YearPeriod", "YearPeriod"}, {"Year", "Year"}, {"Period", "Period"}, {"Date", "Date"}, {"Month", "Month"}, {"QtrID", "QtrID"}, {"Qtr", "Qtr"}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns", {{"YearPeriod", type text}, {"Year", Int64.Type}, {"Period", type text}, {"Date", type datetime}, {"Month", type text}, {"QtrID", type text}, {"Qtr", type text}})
				in
				    #"Changed Type"

	annotation __PBI_LegacyCustomDateTable = true

