table Fact
	isHidden
	lineageTag: 4c3c8069-4524-4093-a87d-f4962e3ae5e1

	measure 'Total Revenue' = SUM([Revenue])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 227b829a-2442-4fd9-b6d0-6b06f6bb5b24

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Sum of Material Costs' = SUM([Material Costs])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 20c3e8c5-5ad5-4cd3-b635-e6d7d5d39636

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Sum of Labor Costs Variable' = SUM([Labor Costs Variable])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: ba18485a-5908-4999-a770-2ae24b44ea2e

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Sum of Taxes' = SUM([Taxes])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 74819a68-7beb-4afe-a888-4915270d2813

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Sum of Rev for Exp Travel' = SUM([Rev for Exp Travel])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 03e3b9bb-3320-43f6-8b24-b98cd802720d

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Sum of Travel Expenses' = SUM([Travel Expenses])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: c41045b0-1c94-47bb-bba8-b9c8b85dc3af

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Sum of Cost Third Party' = SUM([Cost Third Party])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: d648ee89-3550-46ea-bc96-2ac989b2b355

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Sum of Subscription Revenue' = SUM([Subscription Revenue])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: cb320e0a-5ee8-472f-831d-f6268f8a8980

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Gross Margin' = [Total Revenue]-[Total COGS]
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: daa7bac9-30dc-4401-ae20-f35ae778fe0f

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure GM% = DIVIDE([Gross Margin],[Total Revenue])
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 186c271f-1dcd-446b-b0bb-5a3ec872591a

	measure 'YTD Revenue' = TOTALYTD(SUM([Revenue]),'Date'[Date])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: e0775250-0d24-43e5-a380-e757fd83cc86

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Total COGS' = [Sum of Material Costs]+[Sum of Labor Costs Variable]+[Sum of Taxes]+[Sum of Rev for Exp Travel]+[Sum of Travel Expenses]+[Sum of Cost Third Party]
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: d4ecfc9b-6c77-4ff5-b595-b04847d16395

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'YTD COGS' = TOTALYTD([Total COGS],'Date'[Date])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 98d076f4-8c08-485f-bf7a-777271ed6eab

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'YTD Gross Margin' = TOTALYTD([Gross Margin],'Date'[Date])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 73e5bcc1-beb6-4845-82f4-018cb77185dd

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Revenue SPLY' = CALCULATE([Total Revenue],SAMEPERIODLASTYEAR('Date'[Date]))
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 4c3d33f5-3d23-40a0-81db-c0e54c7ad6d5

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Gross Margin SPLY' = CALCULATE([Gross Margin],SAMEPERIODLASTYEAR('Date'[Date]))
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 8786a7d5-ef0f-4702-a7e8-907b05405913

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'GM% SPLY' = [Gross Margin SPLY]/[Revenue SPLY]
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 2e23335e-89bc-4864-a517-33db1111fdcd

	measure 'YTD GM%' = [YTD Gross Margin]/[YTD Revenue]
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 79bf70e2-7a76-4980-ab95-f012a5a90513

	measure 'YTD Revenue SPLY' = CALCULATE([YTD Revenue],SAMEPERIODLASTYEAR(DATESYTD('Date'[Date])))
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 4f45be13-0416-4623-b8a6-73b7718c598b

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'COGS SPLY' = CALCULATE([Total COGS],SAMEPERIODLASTYEAR('Date'[Date]))
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: be242f5f-dd69-4554-8e1c-160f8905ef9a

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'YTD COGS SPLY' = CALCULATE([YTD COGS],SAMEPERIODLASTYEAR(DATESYTD('Date'[Date])))
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: e555245c-57ea-435b-9a5e-8d3da04c0966

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'YTD GM% SPLY' = [YTD GM SPLY]/[YTD Revenue SPLY]
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: ec7a5cb9-d6c4-4333-8749-9c288ce1fa44

	measure 'YTD GM SPLY' = CALCULATE([YTD Gross Margin],SAMEPERIODLASTYEAR(DATESYTD('Date'[Date])))
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 6ec1c2a5-d5be-48c0-8b27-9c7039cc6459

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'YoY Rev Var' = [Total Revenue]-[Revenue SPLY]
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 4ec2a091-cf4d-45f1-ba7b-3c893b1b161d

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'YoY GM Var' = [Gross Margin]-[Gross Margin SPLY]
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: a528961f-6d7d-46b1-8c53-1cced88a4a00

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'YoY Rev Growth' = IF([Revenue SPLY],[YoY Rev Var]/[Revenue SPLY],BLANK())
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: fc2f6810-ff5f-484d-a93a-350cddcc8c87

	measure 'YoY GM Growth' = IF([Gross Margin SPLY],[YoY GM Var]/[Gross Margin SPLY],BLANK())
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: d306ba86-415c-48e1-b3be-f94a5be66107

	measure 'YoY YTD Rev Var' = [YTD Revenue]-[YTD Revenue SPLY]
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: b2ad7969-3f1d-4c49-93fd-9b7868b42f55

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'YoY COGS Var' = [Total COGS]-[COGS SPLY]
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 3500afc8-91a5-4d23-93b7-4aaac34a3585

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'YoY YTD COGS Var' = [YTD COGS]-[YTD COGS SPLY]
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 8440a356-e2fb-48ed-ad76-2abe92c93fcf

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'YoY YTD GM% Var' = [YTD GM%]-[YTD GM% SPLY]
		formatString: #,0
		lineageTag: 8e1d5596-65f9-486a-ae01-579de23deae3

	measure 'YoY YTD GM Var' = [YTD Gross Margin]-[YTD GM SPLY]
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: c755332a-db20-4af6-8429-b1f423c9e3ec

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'YoY GM %Var' = [GM%]-[GM% SPLY]
		lineageTag: f167197a-f6b4-4d76-a51b-b5b1a3d52a4a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'YoY YTD Rev Growth' = IF([YTD Revenue SPLY],[YoY YTD Rev Var]/[YTD Revenue SPLY],BLANK())
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 848e5c39-3abb-4b5b-9830-88e24be9a238

	measure 'YoY COGS Growth' = IF([COGS SPLY],[YoY COGS Var]/[COGS SPLY],BLANK())
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 337c7717-6951-48c6-bad7-b8f2c075a7fa

	measure 'YoY YTD COGS Growth' = IF([YTD COGS SPLY],[YoY YTD COGS Var]/[YTD COGS SPLY],BLANK())
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: e0e24498-87ad-4e1f-b51b-7b4dfa8be99b

	measure 'YoY YTD GM Growth' = IF([YTD GM SPLY],[YoY YTD GM Var]/[YTD GM SPLY],BLANK())
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 06de5ae8-c409-4d29-8992-0888e09f028c

	measure '# of Customers' = DISTINCTCOUNT([Customer Key])
		lineageTag: cae8d2b2-84c5-4f5d-9438-aca01fc6641a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '# of Products' = DISTINCTCOUNT([Product Key])
		lineageTag: ee517f78-47bb-4394-8a82-43506e01f56f

		annotation PBI_FormatHint = {"isText":true}

	measure 'Revenue Budget' = CALCULATE([Total Revenue], FILTER(Scenario, Scenario[Scenario]="Budget"))
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 292b25c3-d790-4722-bbd7-9604a349119a

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Revenue Var to Budget' = [RevenueTY]-[Revenue Budget]
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 1f56656f-7325-4102-a552-fb9fd7c799a0

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Revenue Var % to Budget' = DIVIDE([Revenue Var to Budget], [RevenueTY])
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: cf8e85bd-be31-4072-8d1a-966797ab89ae

	measure RevenueTY = CALCULATE([Total Revenue], FILTER(Scenario, Scenario[Scenario]="Actual"))
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 7689ada9-46cb-4f62-8c7b-1a0825dd0bb9

		kpi
			targetExpression = 'Fact'[Revenue Budget]
			targetFormatString: \$#,0;(\$#,0);\$#,0
			statusGraphic: Traffic Light - Single
			statusExpression = ```
				var x='Fact'[RevenueTY]/'Fact'[_RevenueTY Goal] return
				if(ISBLANK(x),BLANK(),
				        If(x<0.95,-1,
					    If(x<1,0,1)
				    )
				)
				
				```

			annotation GoalType = Measure

			annotation KpiStatusType = Linear

			annotation KpiThresholdType = Percentage

			annotation KpiThresholdOrdering = Ascending

			annotation KpiThresholdCount = 2

			annotation KpiThreshold_0 = 95

			annotation KpiThreshold_1 = 100

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Sum of Revenue' = SUM('Fact'[Revenue])
		lineageTag: 08365799-4585-45ae-b95c-4849c9dd878b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Customer Key'
		dataType: int64
		isHidden
		lineageTag: 434b8926-5096-4b0c-bed8-fe823c28cfeb
		summarizeBy: none
		sourceColumn: Customer Key

		annotation DataTypeAtRefresh = Int64#####not a type

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Product Key'
		dataType: string
		isHidden
		lineageTag: 3eff8167-8afa-4ece-a055-e54500e2e743
		summarizeBy: none
		sourceColumn: Product Key

		annotation DataTypeAtRefresh = String#####not a type

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column 'BU Key'
		dataType: double
		isHidden
		lineageTag: 61e61155-6f9a-4cf5-bbe1-ccd626281dd5
		summarizeBy: none
		sourceColumn: BU Key

		annotation DataTypeAtRefresh = Double#####not a type

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Scenario Key'
		dataType: int64
		isHidden
		lineageTag: ca6d2866-9eec-479c-8da2-df4d75902aa1
		summarizeBy: none
		sourceColumn: Scenario Key

		annotation DataTypeAtRefresh = Int64#####not a type

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Revenue
		dataType: double
		isHidden
		lineageTag: 2bf78e59-108d-46ac-93e8-cc50b6efcf47
		summarizeBy: sum
		sourceColumn: Revenue

		annotation DataTypeAtRefresh = Double#####not a type

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Material Costs'
		dataType: double
		isHidden
		lineageTag: 060f702e-3d1e-43ad-b2ac-36d4f68f2041
		summarizeBy: sum
		sourceColumn: Material Costs

		annotation DataTypeAtRefresh = Double#####not a type

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Labor Costs Variable'
		dataType: double
		isHidden
		lineageTag: e0a6d073-1cb3-443b-ab46-426e2fe0c4a9
		summarizeBy: sum
		sourceColumn: Labor Costs Variable

		annotation DataTypeAtRefresh = Double#####not a type

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Taxes
		dataType: double
		isHidden
		lineageTag: 9e389da2-7e9d-41a2-9c63-40e933918995
		summarizeBy: sum
		sourceColumn: Taxes

		annotation DataTypeAtRefresh = Double#####not a type

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Rev for Exp Travel'
		dataType: double
		isHidden
		lineageTag: c9066e20-09b3-46c7-ac50-0b8a053f873c
		summarizeBy: sum
		sourceColumn: Rev for Exp Travel

		annotation DataTypeAtRefresh = Double#####not a type

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Travel Expenses'
		dataType: double
		isHidden
		lineageTag: c5866d0b-6ef8-405f-885a-58597f0ca0af
		summarizeBy: sum
		sourceColumn: Travel Expenses

		annotation DataTypeAtRefresh = Double#####not a type

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Cost Third Party'
		dataType: double
		isHidden
		lineageTag: 25cf4d64-fc29-46b8-84ea-e13ccfcb03fd
		summarizeBy: sum
		sourceColumn: Cost Third Party

		annotation DataTypeAtRefresh = Double#####not a type

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Subscription Revenue'
		dataType: double
		isHidden
		lineageTag: 8b0a90e2-7526-4d92-8f86-84781348eecf
		summarizeBy: sum
		sourceColumn: Subscription Revenue

		annotation DataTypeAtRefresh = Double#####not a type

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column YearPeriod
		dataType: string
		isHidden
		lineageTag: 04113536-23a7-4e26-9fda-b8f7a2a3adae
		summarizeBy: none
		sourceColumn: YearPeriod

		annotation DataTypeAtRefresh = String#####not a type

		annotation SummarizationSetBy = Automatic

	partition Fact = m
		source =
				let
				    Source = Sql.Database(".", "IP", [Query="SELECT #(lf)       concat([GJAHR] , substring([PERDE], 2, 2) ) + 400 YearPeriod#(lf)      ,[KNDNR] [Customer Key]#(lf)      --,[ARTNR] [Product]#(lf)      --,[FKART] [Billing Type]#(lf)      --,[FRWAE] [Currency Key]#(lf)      --,[VTWEG] [Distribution Channel]#(lf)   ,[VTWEG] [Product Key]#(lf)      --,[PRCTR] [Profit Center]#(lf)   ,pc.[Profit Center Key] [BU Key]#(lf)   ,1 [Scenario Key]#(lf)      --,[KMMAKL] [Material Group]#(lf)      ,[ERLOS]*1.20 [Revenue]#(lf)      ,[VVMAT] [Material Costs]#(lf)      ,[VVLCV] [Labor Costs Variable]#(lf)      ,[VVN30] [Taxes]#(lf)      ,[VV910] [Rev for Exp Travel]#(lf)      ,[VV950] [Travel Expenses]#(lf)      ,[VV970] [Cost Third Party]#(lf)      ,[VVYSV] [Subscription Revenue]#(lf)  FROM OSQ.[osq].[CE11010] f, mds.mdm.profitcenter pc#(lf)where  [MANDT]  = 210 and concat([GJAHR] , substring([PERDE], 2, 2) ) < 201012 and f.PRCTR = pc.PCName and [FRWAE] = 'USD'#(lf)union all #(lf)SELECT #(lf)       concat([GJAHR] , substring([PERDE], 2, 2) ) + 400 PeriodYear#(lf)      ,[KNDNR] [Customer]#(lf)      --,[ARTNR] [Product]#(lf)      --,[FKART] [Billing Type]#(lf)      --,[FRWAE] [Currency Key]#(lf)      --,[VTWEG] [Distribution Channel]#(lf)   ,[VTWEG] [Product Key]#(lf)      --,[PRCTR] [Profit Center]#(lf)   ,pc.[Profit Center Key] [BU Key]#(lf)   ,2 [Scenario Key]#(lf)      --,[KMMAKL] [Material Group]#(lf)      ,[ERLOS]*1.4 [Revenue]#(lf)      ,[VVMAT] [Material Costs]#(lf)      ,[VVLCV] [Labor Costs Variable]#(lf)      ,[VVN30] [Taxes]#(lf)      ,[VV910] [Rev for Exp Travel]#(lf)      ,[VV950] [Travel Expenses]#(lf)      ,[VV970] [Cost Third Party]#(lf)      ,[VVYSV] [Subscription Revenue]#(lf)  FROM OSQ.[osq].[CE11010] f tablesample (85 percent),  mds.mdm.profitcenter pc#(lf)where  [MANDT]  = 300 and concat([GJAHR] , substring([PERDE], 2, 2) ) < 201012 and f.PRCTR = pc.PCName and [FRWAE] = 'USD'"]),
				    #"Renamed Columns" = Table.RenameColumns(Source, {{"Customer Key", "Customer Key"}, {"Product Key", "Product Key"}, {"BU Key", "BU Key"}, {"Scenario Key", "Scenario Key"}, {"Revenue", "Revenue"}, {"Material Costs", "Material Costs"}, {"Labor Costs Variable", "Labor Costs Variable"}, {"Taxes", "Taxes"}, {"Rev for Exp Travel", "Rev for Exp Travel"}, {"Travel Expenses", "Travel Expenses"}, {"Cost Third Party", "Cost Third Party"}, {"Subscription Revenue", "Subscription Revenue"}, {"YearPeriod", "YearPeriod"}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns", {{"Customer Key", Int64.Type}, {"Product Key", type text}, {"BU Key", type number}, {"Scenario Key", Int64.Type}, {"Revenue", type number}, {"Material Costs", type number}, {"Labor Costs Variable", type number}, {"Taxes", type number}, {"Rev for Exp Travel", type number}, {"Travel Expenses", type number}, {"Cost Third Party", type number}, {"Subscription Revenue", type number}, {"YearPeriod", type text}})
				in
				    #"Changed Type"

