table BU
	lineageTag: 689cae2c-05a4-4615-8fe5-24fe2a4df3b2

	column 'BU Key'
		dataType: double
		isHidden
		lineageTag: f1dbeca9-6eed-4be8-bb38-9a5de1bbf694
		summarizeBy: none
		sourceColumn: BU Key

		annotation DataTypeAtRefresh = Double#####not a type

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column BU
		dataType: string
		lineageTag: 0a70f3c5-f257-46f5-8e1c-f81b00b4bd66
		summarizeBy: none
		sourceColumn: BU

		annotation DataTypeAtRefresh = String#####not a type

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column Division
		dataType: string
		lineageTag: 339f42f2-f1e8-4adc-bdc1-ba12a886aad4
		summarizeBy: none
		sourceColumn: Division

		annotation DataTypeAtRefresh = String#####not a type

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column Executive_id
		dataType: int64
		isHidden
		lineageTag: 912dc005-7e4a-4144-bc23-0a2ef62264d7
		summarizeBy: none
		sourceColumn: Executive_id

		annotation DataTypeAtRefresh = Int64#####not a type

		annotation SummarizationSetBy = Automatic

	hierarchy BUHierarchy
		lineageTag: 873d934c-3a28-48f9-b2b7-3c820450d28e

		level Division
			lineageTag: cc22f081-cf0a-4637-89d0-ffdaefab114d
			column: Division

		level BU
			lineageTag: 29f7c0da-4e79-4612-b022-79d9b175efe4
			column: BU

	partition BU = m
		source =
				let
				    Source = Sql.Database(".", "IP", [Query="SELECT #(lf)       #(lf)      [Profit Center Key] [BU Key],#(lf)   BU,#(lf)   Division, Executive_id#(lf)  FROM [MDS].[mdm].[profitcenter]"]),
				    #"Renamed Columns" = Table.RenameColumns(Source, {{"BU Key", "BU Key"}, {"BU", "BU"}, {"Division", "Division"}, {"Executive_id", "Executive_id"}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns", {{"BU Key", type number}, {"BU", type text}, {"Division", type text}, {"Executive_id", Int64.Type}})
				in
				    #"Changed Type"

