table Customer
	lineageTag: c644c8cb-8ab9-4eb5-b89c-37900df73f53

	column Customer
		dataType: double
		isHidden
		lineageTag: 46ba0e19-f5ca-41bc-8524-2f96118e4077
		summarizeBy: none
		sourceColumn: Customer

		annotation DataTypeAtRefresh = Double#####not a type

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Country/Region
		dataType: string
		lineageTag: d83aefad-61c4-464a-9d67-4c938235d9c2
		summarizeBy: none
		sourceColumn: Country/Region

		annotation DataTypeAtRefresh = String#####not a type

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column Name
		dataType: string
		lineageTag: af09ed39-0020-4d37-a230-3e0ece6b10ab
		summarizeBy: none
		sourceColumn: Name

		annotation DataTypeAtRefresh = String#####not a type

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column City
		dataType: string
		lineageTag: 88348783-15cc-4c60-93bf-d8afca8faf57
		dataCategory: City
		summarizeBy: none
		sourceColumn: City

		annotation DataTypeAtRefresh = String#####not a type

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column 'Postal Code'
		dataType: double
		lineageTag: c97e4541-d247-422f-bf3f-0e8122a70e3f
		dataCategory: PostalCode
		summarizeBy: count
		sourceColumn: Postal Code

		annotation DataTypeAtRefresh = Double#####not a type

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column State
		dataType: string
		lineageTag: 0eca1226-0fa0-4a45-95f8-9bcb63976de0
		dataCategory: StateOrProvince
		summarizeBy: none
		sourceColumn: State

		annotation DataTypeAtRefresh = String#####not a type

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column 'Industry ID'
		dataType: double
		isHidden
		lineageTag: 90db24d1-12fd-4a18-b045-5e095ecad774
		summarizeBy: none
		sourceColumn: Industry ID

		annotation DataTypeAtRefresh = Double#####not a type

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	hierarchy CustomerHierarchy
		lineageTag: f855f0e7-2d57-45ad-9299-6a418c6467af

		level Country
			lineageTag: dcf9951e-56bf-4faa-a7f5-22ed2c4e19c2
			column: Country/Region

		level State
			lineageTag: ff9179e2-2bd0-44f8-9235-49fc9f5f3410
			column: State

		level City
			lineageTag: 21b66ddf-b78b-4c83-a2c2-787e352ec5bc
			column: City

		level 'Postal Code'
			lineageTag: c2529079-6ec4-40b2-95b0-d15983af3117
			column: 'Postal Code'

		level Customer
			lineageTag: c2df0a4f-701b-4b82-a732-5ad539833f9f
			column: Customer

	partition Customer = m
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\mad\Dropbox\Work\Obvience\IP\Customer and Product Profitability\Data\dimCustomer.xlsx"), null, true),
				    Sheet = Source{[Item="Sheet1",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Sheet),
				    #"Renamed Columns" = Table.RenameColumns(#"Promoted Headers", {{"Customer", "Customer"}, {"Country", "Country/Region"}, {"Name", "Name"}, {"City", "City"}, {"Postal Code", "Postal Code"}, {"State", "State"}, {"Industry ID", "Industry ID"}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns", {{"Customer", type number}, {"Country/Region", type text}, {"Name", type text}, {"City", type text}, {"Postal Code", type number}, {"State", type text}, {"Industry ID", type number}})
				 in
				    #"Changed Type"

