table Industry
	lineageTag: faf61576-e25e-456c-9fe2-e9e7c5a8260d

	column ID
		dataType: int64
		isHidden
		isKey
		keepUniqueRows
		lineageTag: 6f4f3d1f-13cc-4b8c-906a-b9c5992a310b
		summarizeBy: none
		sourceColumn: ID

		annotation DataTypeAtRefresh = Int64#####not a type

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Industry
		dataType: string
		keepUniqueRows
		lineageTag: 835c16ae-9fb4-4254-8521-b830628f8610
		isDefaultLabel
		summarizeBy: none
		sourceColumn: Industry

		annotation DataTypeAtRefresh = String#####not a type

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column Image
		dataType: binary
		lineageTag: 52027c7d-f52e-44e5-afb6-38eb0727efb2
		dataCategory: Image
		isDefaultImage
		summarizeBy: none
		sourceColumn: Image

		annotation DataTypeAtRefresh = Binary#####not a type

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Industry = m
		source =
				let
				    Source = Sql.Database(".", "IP", [Query="SELECT [dbo].[Industry].*   FROM [dbo].[Industry]"]),
				    #"Renamed Columns" = Table.RenameColumns(Source, {{"ID", "ID"}, {"Industry", "Industry"}, {"Image", "Image"}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns", {{"ID", Int64.Type}, {"Industry", type text}, {"Image", type binary}})
				in
				    #"Changed Type"

