table Product
	lineageTag: 223d5aae-413f-49a7-b29f-bd43d90319a4

	column 'Product Key'
		dataType: int64
		isHidden
		lineageTag: 53e8d722-bf32-4b2d-9395-474b49d6a918
		summarizeBy: none
		sourceColumn: Product Key

		annotation DataTypeAtRefresh = Int64#####not a type

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Product
		dataType: string
		lineageTag: 8f374353-a375-411c-bcac-5f82ef4d035b
		summarizeBy: none
		sourceColumn: Product

		annotation DataTypeAtRefresh = String#####not a type

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	partition Product = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WMjRQ0lEKzi9LVIrViVYyAvECijJzS4vBfGMQ3yW/KD8dIm8C4rvnJKZkQhVYgAR8PXXNjSBcI5B8aV5eapFSbCwA", BinaryEncoding.Base64), Compression.Deflate))),
				    #"Renamed Columns" = Table.RenameColumns(Source, {{"Column1", "Product Key"}, {"Column2", "Product"}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns", {{"Product Key", Int64.Type}, {"Product", type text}})
				 in
				    #"Changed Type"

