table State
	lineageTag: 16c3cd0e-d9e1-4696-b1f9-b10a03e1b15c

	column StateCode
		dataType: string
		lineageTag: 7fa5fb97-a204-4add-b963-888bc1b2998f
		dataCategory: StateOrProvince
		summarizeBy: none
		sourceColumn: StateCode

		annotation DataTypeAtRefresh = String#####not a type

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column State
		dataType: string
		lineageTag: f7e66d39-ddcf-4828-adf8-98682e5b5b4b
		dataCategory: StateOrProvince
		summarizeBy: none
		sourceColumn: State

		annotation DataTypeAtRefresh = String#####not a type

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column Region
		dataType: string
		lineageTag: 6ff1613d-8db3-4a87-9a8e-ea7707020b0f
		dataCategory: Country
		summarizeBy: none
		sourceColumn: Region

		annotation DataTypeAtRefresh = String#####not a type

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	partition State = m
		source =
				let
				    Source = Sql.Database(".", "IP", [Query="select StateShort StateCode, StateName State, Region from MDS.mdm.state"]),
				    #"Renamed Columns" = Table.RenameColumns(Source, {{"StateCode", "StateCode"}, {"State", "State"}, {"Region", "Region"}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns", {{"StateCode", type text}, {"State", type text}, {"Region", type text}})
				in
				    #"Changed Type"

