table 'Sales Order'
	lineageTag: ee855eee-1d63-4301-8a57-06ecd1b06287

	column Channel
		dataType: string
		lineageTag: 3c6db5db-af11-4d71-8a94-ca796da5686b
		summarizeBy: none
		sourceColumn: Channel

		annotation SummarizationSetBy = Automatic

	column SalesOrderLineKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 9195ac5f-c22a-422f-ab8e-6eb53adefaf9
		summarizeBy: none
		sourceColumn: SalesOrderLineKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Sales Order'
		dataType: string
		lineageTag: 71806129-e79a-4b70-9c3f-869e619aee03
		summarizeBy: none
		sourceColumn: Sales Order

		annotation SummarizationSetBy = Automatic

	column 'Sales Order Line'
		dataType: string
		lineageTag: 2089deef-622f-4340-a831-c6f4d9f17a27
		summarizeBy: none
		sourceColumn: Sales Order Line

		annotation SummarizationSetBy = Automatic

	hierarchy 'Sales Orders'
		lineageTag: 50630276-1986-4b90-859f-f355f7d16941

		level 'Sales Order'
			lineageTag: ca6d2a41-6a22-4279-9e43-ddbb04358e53
			column: 'Sales Order'

		level 'Sales Order Line'
			lineageTag: 9cd68f7e-3e43-402f-b959-3e2f98e2142c
			column: 'Sales Order Line'

	partition 'Sales Order-29c8461f-8ea7-4acf-8676-6ade54d1e2a0' = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\jterh\OneDrive - Microsoft\_Corp Era\Power BI\AW2020 Sample\Sales\AdventureWorks Sales.xlsx"), null, true),
				    SalesOrder_Table = Source{[Item="SalesOrder",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(SalesOrder_Table,{{"Channel", type text}, {"SalesOrderLineKey", Int64.Type}, {"Sales Order", type text}, {"Sales Order Line", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

